#!/bin/bash
# This script extracts the cluster sizes obtained at the maximum
# of the partition density of the EdgeLinkage.pl algorithm (maximum
# that can be obtained using the "EdgeLinkage_commands4maximum.sh") 
# and order them in increasing size order. Clusters are obtained from
# the "Clusters" files generated by EdgeLinkage.pl
###########################
# Silwood Park (ICL)
# July 7th, 2016
# Alberto Pascual-García
##########################
#
#
# --- generic label for the input file
number=50
method=Average
threshold=129
# --- specific label for function graphs
function=ATP7
# --- define the file here
#file=Clusters-NL_"$method"_StopStep-"$threshold"_FunctGroups_SingleFunctions_"$function"_Zeros-Intercept.txt
file=Clusters-NL_"$method"_StopStep-"$threshold".out

echo
echo Extract the $number largest clusters for $file and threshold $threshold:
echo ClusterId / Number of Edges / Number of Nodes
echo

grep INFO $file  | sort -k 3,3 -n | tail -n $number

echo
