############################
#   nodeLinkage_analysis.R
############################
#
# This script takes the compact History file generated by NodeLinkage.pl
# and extracts the maximum values for the partition densities measures, together
# with a summary plot
############################
# USAGE: Provide path and name of the history compact file as indicated below.
# OUTPUT: The step at which the partition densities are maximum, and a summary plot of the partition densities.
############################

library(ggplot2)

# --- Load the history compact file (NodeLinkage output)
dir="path to dir of history compact file"
setwd(dir)

# Set the input file and label for the output file
file.hist="history file name"
label="something" # a string with a description for your output file

# ---- STOP EDITING HERE 

hist.comp=read.table(file=file.hist,sep="\t",header = TRUE) # for current NodeLink.pl version (Dec 2018)

# --- Plot
system(command="mkdir -p figures")
setwd("figures")
fileOut=paste("Plot_PartitionDensityVsStep_",label,".pdf",sep="")
pdf(file=fileOut,width=10,height=8)
print(ggplot(data = hist.comp) + 
  geom_point(mapping = aes(x=Step,y=Density,color="Total"))+
  geom_point(mapping = aes(x=Step,y=DensityInt,color="Internal"),shape=2)+
  geom_point(mapping = aes(x=Step,y=DensityExt,color="External"),shape=6) + 
  geom_line(mapping = aes(x=Step,y=Density,color="Total"))+
  geom_line(mapping = aes(x=Step,y=DensityInt,color="Internal"))+
  geom_line(mapping = aes(x=Step,y=DensityExt,color="External"))+
  xlab("Clustering Step")+
  theme(legend.title =  element_blank(),
        axis.text = element_text(size=20),axis.title = element_text(size=24),
        legend.text =element_text(size=18)))
dev.off()

# --- Retrieve maximumu and report
maxDens=hist.comp$Step[which.max(hist.comp$Density)]
maxDensExt=hist.comp$Step[which.max(hist.comp$DensityExt)]
maxDensInt=hist.comp$Step[which.max(hist.comp$DensityInt)]

print("Maximum total partition density found at step =")
print(maxDens,digits=3)
print("Maximum external partition density found at step =")
print(maxDensExt,digits=3)
print("Maximum internal partition density found at step =")
print(maxDensInt,digits=3)

